# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant::Util::Platform::windows? then
  	config.vm.box = "maxx/ubuntu16"
  else
  	config.vm.box = "bento/ubuntu-14.04"
  end

  config.env.enable
  config.vm.hostname = ENV["VM_HOSTNAME"]
  config.vm.network 'private_network', ip: '10.1.1.34'
  config.vm.provision :shell, path: './install.sh'
  config.vm.provision 'shell', inline: "hostname #{config.vm.hostname}"
end

